mongo-appointment-db:
  image: mongo
  restart: always
  ports:
    - "27017:27017"
  environment:
    MONGO_INITDB_ROOT_USERNAME: mongolocal
    MONGO_INITDB_ROOT_PASSWORD: mongolocal
  volumes:
    - .dockervolumes/mongo-data:/data/db
